version: "3"

services:

  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8080:80
    volumes:
      - ./dist/:/var/www/html/wp-content/themes/judolosser/
      - ./wordpress/plugins/:/var/www/html/wp-content/plugins/
      - ./wordpress/uploads/:/var/www/html/wp-content/uploads/
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DEBUG: 1
      ENVIRONMENT: ${ENVIRONMENT}
  mariadb:
    image: mariadb:10.2.11
    ports:
      - 3307:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root