version: "3"

services:

  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8080:80
    volumes:
      - ./wordpress/:/var/www/html/
    links:
      - mariadb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: root

  mariadb:
    image: mariadb:10.2.11
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root