version: "3.2"

services:
  php-fpm:
    build:
      context: './docker/php/'
    networks:
      - backend
    volumes:
      - ./web/:/var/www/web/:delegated
      - ./vendor/:/var/www/vendor/:delegated
      - ./config/:/var/www/config/:delegated
      - ${PWD}/.env:/var/www/.env:delegated
    container_name: judolosser-php

  apache:
    build:
      context: './docker/apache/'
    depends_on:
      - php-fpm
      - mariadb
    networks:
      - frontend
      - backend
    volumes:
      - ./web/:/var/www/web/:delegated
      - ./vendor/:/var/www/vendor/:delegated
      - ./config/:/var/www/config/:delegated
      - ${PWD}/.env:/var/www/.env:delegated
    ports:
      - 8080:80
    container_name: judolosser-apache

  mariadb:
    image: mariadb:10.5
    networks:
      - backend
    ports:
      - 3307:3306
    volumes:
      - ./docker/mariadb:/var/lib/mysql:delegated
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    container_name: judolosser-mariadb

networks:
  frontend:
  backend: